// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfzW8yAJQgveOdS8JeS4_I0KcUqepxFQ',
    appId: '1:305336509027:web:3bf23b55b2ab679f334e56',
    messagingSenderId: '305336509027',
    projectId: 'pntecom-6cc92',
    authDomain: 'pntecom-6cc92.firebaseapp.com',
    storageBucket: 'pntecom-6cc92.appspot.com',
    measurementId: 'G-ELH4N3009D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOqHXwrm49G1E3RbX88V9rtQGiOIrqc4',
    appId: '1:305336509027:android:5f896d5102bad7cd334e56',
    messagingSenderId: '305336509027',
    projectId: 'pntecom-6cc92',
    storageBucket: 'pntecom-6cc92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkSCljxOxfLEc8PwXf66eZ-gNjIPTmP0M',
    appId: '1:305336509027:ios:8d82e01df3484bc0334e56',
    messagingSenderId: '305336509027',
    projectId: 'pntecom-6cc92',
    storageBucket: 'pntecom-6cc92.appspot.com',
    iosClientId: '305336509027-4ql85u1kvcoq6h4vtkplvqlumfjdtb31.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseFirebaseAcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkSCljxOxfLEc8PwXf66eZ-gNjIPTmP0M',
    appId: '1:305336509027:ios:fda87a7eca464bc5334e56',
    messagingSenderId: '305336509027',
    projectId: 'pntecom-6cc92',
    storageBucket: 'pntecom-6cc92.appspot.com',
    iosClientId: '305336509027-iri49m8quhrptvvpn4po82a0n02t60a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseFirebaseAcc.RunnerTests',
  );
}
